In [1]:
import pandas as pd
import numpy as np

# Data Frames

In [2]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [11]:
df = pd.DataFrame(data, columns=columns)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

**we can also use list of dictionary to create dataframe**

In [12]:

data = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    {
        "Make": "Lotus",
        "Model": "Elise",
        "Year": 2010,
        "Engine HP": 218.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "convertible",
        "MSRP": 54990
    },
    {
        "Make": "GMC",
        "Model": "Acadia",
        "Year": 2017,
        "Engine HP": 194.0,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "4dr SUV",
        "MSRP": 34450
    },
    {
        "Make": "Nissan",
        "Model": "Frontier",
        "Year": 2017,
        "Engine HP": 261.0,
        "Engine Cylinders": 6,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "Pickup",
        "MSRP": 32340
    }
]

In [13]:
pd.DataFrame(data)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [16]:
df.head(n=3)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

# Series

In [17]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [18]:
df['Make']

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [ ]:
df['Engine HP']   #to access columns having spaces

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

In [22]:
df[['Make', 'Model']]

      Make     Model
0   Nissan    Stanza
1  Hyundai    Sonata
2    Lotus     Elise
3      GMC    Acadia
4   Nissan  Frontier

**To add column**

In [ ]:
data = df.drop(columns=['S.N'])  #using column argument

In [52]:
df.drop(columns=['data'], inplace=True)

In [53]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [ ]:
del df['id']     #directly delete a column

In [57]:
df

,S.N,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,1,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,2,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,3,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,4,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,5,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

**To add new columns**

In [54]:
new_columnn = [1,2,3,4,5]
data = df.insert(0, 'S.N', new_columnn)

In [55]:
df

,S.N,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,1,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,2,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,3,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,4,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,5,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

# index

In [58]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [61]:
df.Make.index

RangeIndex(start=0, stop=5, step=1)

In [70]:
df.loc[[1, 2]]

,S.N,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,2,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,3,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

In [73]:
df.index = ['a', 'b', 'c','d', 'e']
df

,S.N,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,1,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,2,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,3,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,4,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
e,5,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [80]:
df.loc['a', 'Make']

'Nissan'

In [86]:
df.loc[df['S.N']>=1, ['Make', 'Model']]

      Make     Model
a   Nissan    Stanza
b  Hyundai    Sonata
c    Lotus     Elise
d      GMC    Acadia
e   Nissan  Frontier

In [89]:
df.iloc[0:2]

,S.N,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,1,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,2,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

**Reset index**

In [90]:
df.reset_index()

,index,S.N,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,a,1,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,b,2,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,c,3,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,d,4,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,e,5,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [91]:
df.reset_index(drop=True)

,S.N,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,1,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,2,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,3,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,4,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,5,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [92]:
df

,S.N,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,1,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,2,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,3,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,4,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
e,5,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [94]:
df = df.reset_index(drop=True)
df

,S.N,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,1,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,2,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,3,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,4,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,5,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340